SET
FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE post;
SET
FOREIGN_KEY_CHECKS = 1;

INSERT INTO post (id,
                  title,
                  content,
                  receive_method,
                  return_method,
                  return_address1,
                  return_address2,
                  deposit,
                  fee,
                  is_banned,
                  embedding_status,
                  author_id,
                  category_id,
                  embedding_version,
                  created_at,
                  modified_at)
VALUES (1,
        '고프로 HERO12 대여합니다',
        '상태 최상, 액션캠 촬영 가능. 배터리 2개 포함.',
        'DIRECT',
        'DIRECT',
        '서울특별시 강남구',
        '역삼동',
        50000,
        10000,
        FALSE,
        'WAIT',
        1,
        10,
        0,
        NOW(),
        NOW()),
       (2,
        '맥북 프로 14 M3 대여',
        '하루 단위 대여 가능, 충전기 포함.',
        'DELIVERY',
        'DELIVERY',
        '성남시',
        '분당동',
        300000,
        20000,
        FALSE,
        'WAIT',
        2,
        9,
        0,
        NOW(),
        NOW()),
       (3,
        '축구공 대여 (풋살용)',
        '상태 좋음, 직거래만 가능합니다.',
        'DIRECT',
        'DIRECT',
        '서울특별시 서초구',
        '반포동',
        10000,
        3000,
        FALSE,
        'WAIT',
        1,
        5,
        0,
        NOW(),
        NOW());
